title: Lavori sulla casa a San Giovenale
email: your-email@domain.com
description: " Lavori svolti nel rifacimento della nostra casa a San Giovenale."
baseurl: ""
url: "http://sangiovenale.github.io"
timezone: Europe/Rome

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
